berlin: Berlin
hamburg: Hamburg
muenchen: München
dortmund: Dortmund
bielefeld: Bielefeld
bonn: Bonn
braunschweig: Braunschweig
chemnitz: Chemnitz
dresden: Dresden
neustadt: Neustadt
oldenburg: Oldenburg
saarbruecken: Saarbrücken
schweinfurt: Schweinfurt