berlin: Berlin
duesseldorf: Düsseldorf
hamburg: Hamburg
hannover: Hannover
muenchen: München
dortmund: Dortmund
bielefeld: Bielefeld
bonn: Bonn
braunschweig: Braunschweig
chemnitz: Chemnitz
dresden: Dresden
koeln: Köln
neustadt: Neustadt
nuernberg: Nürnberg
oldenburg: Oldenburg
saarbruecken: Saarbrücken
schweinfurt: Schweinfurt
stuttgart: Stuttgart